var users = {
  viethle126: {
    password: 'hoot',
    name: 'Viet Le',
    handle: 'viethle126',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  alysiasaquil: {
    password: 'hoot',
    name: 'Alysia Saquilabon',
    handle: 'alysiasaquil',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  ajames91: {
    password: 'hoot',
    name: 'Andrew Velasquez',
    handle: 'ajames91',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  arunpaulgopal: {
    password: 'hoot',
    name: 'Arun Gopal',
    handle: 'arunpaulgopal',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  bgnewuch: {
    password: 'hoot',
    name: 'Benjamin Gnewuch',
    handle: 'bgnewuch',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  brianwalen: {
    password: 'hoot',
    name: 'Brian Walen',
    handle: 'brianwalen',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  metcalfec: {
    password: 'hoot',
    name: 'Chris Metcalfe',
    handle: 'metcalfec',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  coreysl: {
    password: 'hoot',
    name: 'Corey Lin ',
    handle: 'coreysl',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  nanhyunchul: {
    password: 'hoot',
    name: 'Hyun Lee',
    handle: 'nanhyunchul',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  jnguyen: {
    password: 'hoot',
    name: 'Justin Nguyen',
    handle: 'jnguyen',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  little78926: {
    password: 'hoot',
    name: 'John Huang',
    handle: 'little78926',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  mikefield: {
    password: 'hoot',
    name: 'Michael Field',
    handle: 'mikefield',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  treezrppl2: {
    password: 'hoot',
    name: 'Nathan Walston',
    handle: 'treezrppl2',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  niralpokal: {
    password: 'hoot',
    name: 'Niral Pokal',
    handle: 'niralpokal',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  ronperris: {
    password: 'hoot',
    name: 'Ron Perris',
    handle: 'ronperris',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  espressohoarder: {
    password: 'hoot',
    name: 'Shlomo Kofman',
    handle: 'espressohoarder',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  tputs001: {
    password: 'hoot',
    name: 'Tom Putsawatanachai',
    handle: 'tputs001',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
  zane: {
    password: 'hoot',
    name: 'Zane DeFazio',
    handle: 'zane',
    tweets: [],
    followers: [],
    following: [],
    notifications: [],
    favorites: [],
  },
}

module.exports = users;
